# Generated by Django 6.0.5 on 2026-05-15 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ENO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ENO',
                'verbose_name_plural': 'ENO',
                'ordering': ['region', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('niveau', models.CharField(choices=[('LICENCE', 'Licence'), ('MASTER', 'Master')], default='LICENCE', max_length=20)),
                ('est_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Spécialité',
                'verbose_name_plural': 'Spécialités',
                'ordering': ['niveau', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Cohorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('annee_academique', models.CharField(max_length=9)),
                ('statut', models.CharField(choices=[('IMPORTEE', 'Importée'), ('PRETE', 'Prête'), ('EN_COURS', 'Regroupement en cours'), ('REGROUPEE', 'Regroupée'), ('VALIDEE', 'Validée')], default='IMPORTEE', max_length=20)),
                ('nb_apprenants', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohortes_creees', to=settings.AUTH_USER_MODEL)),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohortes', to='core.specialite')),
            ],
            options={
                'verbose_name': 'Cohorte',
                'verbose_name_plural': 'Cohortes',
                'ordering': ['-annee_academique', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Apprenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ine', models.CharField(max_length=50, unique=True, verbose_name='INE')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apprenant_profil', to=settings.AUTH_USER_MODEL)),
                ('cohorte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apprenants', to='core.cohorte')),
                ('eno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apprenants', to='core.eno')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apprenants', to='core.specialite')),
            ],
            options={
                'verbose_name': 'Apprenant',
                'verbose_name_plural': 'Apprenants',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('IMPORT_CSV', 'Import CSV'), ('LANCEMENT_CGA', 'Lancement CGA'), ('VALIDATION_GROUPES', 'Validation des groupes'), ('AJUSTEMENT_MANUEL', 'Ajustement manuel'), ('EXPORT_CSV', 'Export CSV'), ('EXPORT_PDF', 'Export PDF'), ('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion')], max_length=30)),
                ('description', models.TextField()),
                ('objet_type', models.CharField(blank=True, max_length=50)),
                ('objet_id', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Regroupement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w1', models.FloatField(default=0.7, verbose_name='Poids géographique (w₁)')),
                ('w2', models.FloatField(default=0.3, verbose_name='Poids institutionnel (w₂)')),
                ('taille_min', models.PositiveIntegerField(default=3)),
                ('taille_max', models.PositiveIntegerField(default=6)),
                ('nb_generations', models.PositiveIntegerField(default=200)),
                ('taille_population', models.PositiveIntegerField(default=100)),
                ('seed', models.PositiveIntegerField(default=42)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', "En cours d'exécution"), ('TERMINE', 'Terminé'), ('VALIDE', 'Validé'), ('ERREUR', 'Erreur')], default='EN_ATTENTE', max_length=20)),
                ('d_geo_final', models.FloatField(blank=True, null=True, verbose_name='D_geo final (km)')),
                ('p_eno_final', models.FloatField(blank=True, null=True, verbose_name='P_ENO final')),
                ('fitness_final', models.FloatField(blank=True, null=True)),
                ('nb_groupes', models.PositiveIntegerField(blank=True, null=True)),
                ('nb_hors_eno', models.PositiveIntegerField(blank=True, null=True)),
                ('variance_territoriale', models.FloatField(blank=True, null=True)),
                ('temps_execution_sec', models.FloatField(blank=True, null=True)),
                ('message_erreur', models.TextField(blank=True)),
                ('progression_data', models.JSONField(blank=True, default=list)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cohorte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regroupements', to='core.cohorte')),
                ('lance_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regroupements_lances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regroupement',
                'verbose_name_plural': 'Regroupements',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('dist_moy_km', models.FloatField(default=0.0, verbose_name='Distance moyenne (km)')),
                ('dist_max_km', models.FloatField(default=0.0, verbose_name='Distance maximale (km)')),
                ('nb_hors_eno', models.PositiveIntegerField(default=0, verbose_name='Nb apprenants hors ENO')),
                ('taille', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cohorte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='core.cohorte')),
                ('eno_rattachement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groupes', to='core.eno')),
                ('regroupement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='core.regroupement')),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
                'ordering': ['regroupement', 'numero'],
                'unique_together': {('regroupement', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='MembreGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_eno_km', models.FloatField(default=0.0)),
                ('est_hors_eno', models.BooleanField(default=False)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appartenances', to='core.apprenant')),
                ('eno_administratif', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membres_administratifs', to='core.eno')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='core.groupe')),
            ],
            options={
                'verbose_name': 'Membre de groupe',
                'verbose_name_plural': 'Membres de groupes',
                'unique_together': {('groupe', 'apprenant')},
            },
        ),
    ]
